# Generated by Django 6.1.1 on 2026-09-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=100)),
            ],
        ),
    ]
