# Generated by Django 6.1.1 on 2026-09-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
    ]
